
# よくあるエラー

このページでは、一般的なエラーの一覧と、トラブルシューティングの方法を紹介します。 

## エラーメッセージの読み方  

Rのエラーは時として不可解なことがあるので、Googleが頼りになります。エラーメッセージを「R」で検索し、[StackExchange.com](StackExchange.com)、[stackoverflow.com](stackoverflow.com)、[community.rstudio.com](community.rstudio.com)、twitter(#rstats)、その他プログラマーが質問や回答を提出するためのフォーラムで最近の投稿を探します。似たような問題を解決した最近の投稿を探してみてください。 


いくら探しても答えが見つからない場合は、*再現可能な例*（"reprex"）を作成して、自分で質問を投稿することを検討してください。再現可能な例を作成してフォーラムに投稿する方法については、[Getting help]のページを参照してください。


## よくあるエラー  

以下に、いくつかの一般的なエラーと、その説明や解決策の可能性を示します。これらのいくつかは、Stack OverflowでRのエラーメッセージに関する最も一般的なフォーラムの投稿を分析したNoam Ross氏の意見を参考にしています（分析結果は[こちら](https://github.com/noamross/zero-dependency-problems/blob/master/misc/stack-overflow-common-r-errors.md)をご覧ください）。 


### 打ち間違いエラー {.unnumbered}  

```
Error: unexpected symbol in:
"  geom_histogram(stat = "identity")+
  tidyquant::geom_ma(n=7, size = 2, color = "red" lty"
```
"unexpected symbol" と表示された場合は、カンマが抜けていないか確認してください。 

### パッケージエラー {.unnumbered}  

```
could not find function "x"...
```

これは、関数名を間違って入力したか、パッケージをインストールまたはロードし忘れた可能性があります。

```
Error in select(data, var) : unused argument (var)
```

`dplyr::select()`を使っているつもりでも、`select()`関数が`MASS::select()`によってマスクされています。`dplyr::`を指定するか、パッケージのロード順を変えて、dplyrが他のパッケージの後に来るようにしてください。

その他の一般的なマスキングエラーは、 `plyr::summary()` や `stats::filter()` です。[**コンフリクトしている** パッケージ](https://www.tidyverse.org/blog/2018/06/conflicted/)の使用を検討してください。


```
Error in install.packages : ERROR: failed to lock directory ‘C:\Users\Name\Documents\R\win-library\4.0’ for modifying
Try removing ‘C:\Users\Name\Documents\R\win-library\4.0/00LOCK’
```

もし、"00LOCK "ファイルを削除しなければならないというエラーが出た場合、コンピュータのディレクトリにある "R "ライブラリ（例：R/win-library/）に行き、"00LOCK "というフォルダを探してください。これを手動で削除して、再度パッケージをインストールしてみてください。以前、インストール作業に中断されて、このような状態になったと考えられます。 


### オブジェクトのエラー {.unnumbered}  

```
No such file or directory:
```
エクスポートまたはインポートしようとしたときに、このようなエラーが表示される場合は、次のことを確認してください。ファイルとファイルパスのスペルを確認してください。また、パスにスラッシュが含まれている場合は、それが前方の `/` であり、後方の `/` ではないことを確認してください。また、正しいファイル拡張子を使用していることを確認してください（例：.csv、.xlsx）。 

```
object 'x' not found 
```

これは、参照しているオブジェクトが存在していないことを意味します。ここよりも前のコードが正しく実行されなかったのではないでしょうか？ 

```
Error in 'x': subscript out of bounds
```

これは、存在しないもの（ベクトルやリストの要素）にアクセスしようとしたことを意味します。 


### 関数の文法エラー {.unnumbered}

```
# ran recode without re-stating the x variable in mutate(x = recode(x, OLD = NEW)
Error: Problem with `mutate()` input `hospital`.
x argument ".x" is missing, with no default
i Input `hospital` is `recode(...)`.
```

上記のエラー（`argument .x is missing, with no default`）は、`mutate()`において、`recode()`や`replace_na()`のように、第一引数にカラム名を指定することが期待される関数を指定している場合によく見られます。これは簡単に忘れてしまいます。


### 論理的エラー {.unnumbered}  

```
Error in if
```

これは、TRUEでもFALSEでもないものに`if`文が適用されたことを意味していると思われます。 


### 因子のエラー {.unnumbered}  

```
#Tried to add a value ("Missing") to a factor (with replace_na operating on a factor)
Problem with `mutate()` input `age_cat`.
i invalid factor level, NA generated
i Input `age_cat` is `replace_na(age_cat, "Missing")`.invalid factor level, NA generated
```

無効な因子レベルに関するこのエラーが表示された場合、因子クラス（あらかじめ定義されたレベルを含む）の列があり、そこに新しい値を追加しようとした可能性があります。新しい値を追加する前に、文字列クラスに変換してください。 


### プロットのエラー {.unnumbered}  

`Error: Insufficient values in manual scale. 3 needed but only 2 provided.`
ggplot() scale_fill_manual() values = c("orange", "purple") ... insufficient for number of factor levels ... consider whether NA is now a factor level...

ggplot() scale_fill_manual() values = c("orange", "purple") ... 因子水準の数が足りない ... NAが因子水準になっているかどうかを検討してください。

```
Can't add x object
```
ggplotのコマンドの最後に余分な`+`がついていルトも思われます。削除しましょう。


### R Markdown エラー {.unnumbered}  

エラーメッセージに`Error in options[[sprintf("fig.%s", i)]]`のような内容が含まれている場合は、各チャンクの先頭にある knitr のオプションが、`out.width = `または`out.height = `を正しく使用しており、`fig.width=`および`fig.height=`を使用して*いない*ことを確認してください。

### その他 {.unnumbered}  

パイプされた **dplyr** 動詞を再配置して、途中でパイプを交換しなかったのか、再配置した後に最後からパイプを削除し忘れていないかを考えてみましょう。



<!-- ======================================================= -->
## リソース { }

こちらは、Rのよくあるエラーについてのブログです: [R programming errors faced by beginners](https://www.r-bloggers.com/2016/06/common-r-programming-errors-faced-by-beginners/)
